<link rel="stylesheet" title="Schulkonsole" href="css/schulkonsole.css" type="text/css">
<!--[if lt IE 7]>
<style type="text/css">@import url(css/schulkonsole_IE.css);</style>
</style>
<![endif]-->

<!--#if expr="$link_settings" -->
<!--#else -->
<style type="text/css">@import url(css/schulkonsole_restricted.css);</style>
<!--[if lt IE 7]>
<style type="text/css">@import url(css/schulkonsole_restricted_IE.css);</style>
</style>
<![endif]-->
<!--#endif -->
