<div id="head">
<!--#if expr="$link_settings" -->
<h1><gettext>Schulkonsole f&uuml;r Netzwerkberater/innen</gettext></h1>
<!--#else -->
	<!--#if expr="$link_class" -->
<h1><gettext>Schulkonsole f&uuml;r Lehrer/innen</gettext></h1>
	<!--#else -->
<h1><gettext>Schulkonsole f&uuml;r Sch&uuml;ler/innen</gettext></h1>
	<!--#endif -->
<!--#endif -->
<img src="img/MOII.jpg" alt="Medienoffensive Schule II">
</div>
<div id="supportnetz">
<a href="http://www.support-netz.de/">[www.support-netz.de]</a>
</div>

<!--#include file="menu.shtml.inc" -->

<div id="special">
</div>

