<div id="header">
<!--#if expr="$link_settings" -->
<h1><gettext>Schulkonsole f&uuml;r Netzwerkberater/innen</gettext></h1>
<!--#else -->
	<!--#if expr="$link_class" -->
<h1><gettext>Schulkonsole f&uuml;r Lehrer/innen</gettext></h1>
	<!--#else -->
<h1><gettext>Schulkonsole f&uuml;r Sch&uuml;ler/innen</gettext></h1>
	<!--#endif -->
<!--#endif -->
<gettext>Version</gettext> <!--#echo var="version" -->
<gettext>f&uuml;r Linux Musterl&ouml;sung 3.0</gettext>
<img src="img/MOII.png" alt="Medienoffensive Schule II">
</div>
<div id="supportnetz">
<a href="http://www.support-netz.de/">[www.support-netz.de]</a>
</div>

<!--#include file="menu.shtml.inc" -->

