<div id="menu">
<!--#if expr="$link_start" -->
   <a href="start"><gettext>Startseite</gettext></a>
<!--#endif -->
<!--#if expr="$link_room" -->
   <a href="room"><gettext>aktueller Raum</gettext></a>
<!--#endif -->
<!--#if expr="$link_class" -->
   <a href="class"><gettext>Klassen</gettext></a>
<!--#endif -->
<!--#if expr="$link_project" -->
   <a href="project"><gettext>Projekte</gettext></a>
<!--#endif -->
<!--#if expr="$link_settings" -->
   <a href="settings"><gettext>Einstellungen</gettext></a>
<!--#endif -->
<!--#if expr="$link_user" -->
   <a href="user"><gettext>Benutzer</gettext></a>
<!--#endif -->
<!--#if expr="$link_quotas" -->
   <a href="quotas"><gettext>Quota</gettext></a>
<!--#endif -->
<!--#if expr="$link_rooms" -->
   <a href="rooms"><gettext>R&auml;ume</gettext></a>
<!--#endif -->
<!--#if expr="$link_printers" -->
   <a href="printers"><gettext>Drucker</gettext></a>
<!--#endif -->
<!--#if expr="$link_hosts" -->
   <a href="hosts"><gettext>Hosts</gettext></a>
<!--#endif -->
<!--#if expr="$link_logout" -->
   <a href="logout"><gettext>Abmelden</gettext></a>
<!--#endif -->
</div>
