<ul>
<!--#if expr="$link_user" -->
	<li><a href="user"><gettext>Start</gettext></a></li>
<!--#endif -->
<!--#if expr="$link_user_students" -->
	<li><a href="user_students"><gettext>Sch&uuml;lerliste pflegen</gettext></a></li>
<!--#endif -->
<!--#if expr="$link_user_teachers" -->
	<li><a href="user_teachers"><gettext>Lehrerliste pflegen</gettext></a></li>
<!--#endif -->
<!--#if expr="$link_user_check" -->
	<li><a href="user_check"><gettext>Benutzerlisten pr&uuml;fen</gettext></a></li>
<!--#endif -->
<!--#if expr="$link_user_commit" -->
	<li><a href="user_commit"><gettext>Benutzerdaten &uuml;bernehmen</gettext></a></li>
<!--#endif -->
<!--#if expr="$link_user_reports" -->
	<li><a href="user_reports"><gettext>Berichte</gettext></a></li>
<!--#endif -->
</ul>
