<p><gettext>Klassenarbeit:</gettext>
<!--#if expr="$done_test_start" -->
<a href="room_test_handout"><gettext>Bereitstellen</gettext></a>
<!--#else -->
<gettext>Bereitstellen</gettext>
<!--#endif -->
-
<!--#if expr="$done_test_handout" -->
<a href="room_test_password"><gettext>Passwort &auml;ndern</gettext></a>
<!--#else -->
<gettext>Passwort &auml;ndern</gettext>
<!--#endif -->
-
<!--#if expr="$done_test_password" -->
<a href="room_test_collect"><gettext>Einsammeln</gettext></a>
<!--#else -->
<gettext>Einsammeln</gettext>
<!--#endif --></p>

<hr>
