use strict;
use utf8;

package Schulkonsole::Error::Cyrus;
require Exporter;
use vars qw($VERSION @ISA @EXPORT @EXPORT_OK %EXPORT_TAGS);
$VERSION = 0.16;
@ISA = qw(Exporter);
@EXPORT_OK = qw(
	OK
	WRAPPER_ERROR_BASE
	WRAPPER_UNAUTHORIZED_UID
	WRAPPER_INVALID_SCRIPT
	WRAPPER_SCRIPT_EXEC_FAILED
	WRAPPER_NO_CYRUS_USER
	WRAPPER_INVALID_EUID
);

# package constants
use constant {
	OK => 0,

	WRAPPER_ERROR_BASE => 9000,
	WRAPPER_UNAUTHORIZED_UID => 9000 -3,
	WRAPPER_INVALID_SCRIPT => 9000 -5,
	WRAPPER_SCRIPT_EXEC_FAILED => 9000 -6,
	WRAPPER_NO_CYRUS_USER => 9000 -7,
	WRAPPER_INVALID_EUID => 9000 -8,
};



1;
