use strict;
use utf8;

package Schulkonsole::Error::Linbo;
require Exporter;
use vars qw($VERSION @ISA @EXPORT @EXPORT_OK %EXPORT_TAGS);
$VERSION = 0.16;
@ISA = qw(Exporter);
@EXPORT_OK = qw(
	OK

	START_CONF_ERROR

	WRAPPER_ERROR_BASE
	WRAPPER_GENERAL_ERROR
	WRAPPER_PROGRAM_ERROR
	WRAPPER_UNAUTHORIZED_UID
	WRAPPER_SCRIPT_EXEC_FAILED
	WRAPPER_UNAUTHENTICATED_ID
	WRAPPER_APP_ID_DOES_NOT_EXIST
	WRAPPER_UNAUTHORIZED_ID
	WRAPPER_INVALID_GROUP
	WRAPPER_INVALID_FILENAME
	WRAPPER_INVALID_IS_EXAMPLE
	WRAPPER_INVALID_IMAGE
	WRAPPER_INVALID_ACTION
	WRAPPER_CANNOT_OPEN_FILE
	WRAPPER_CANNOT_RUN_COMMAND
	WRAPPER_INVALID_TYPE
	WRAPPER_INVALID_TARGET
	WRAPPER_NO_SUCH_HOST
	WRAPPER_NO_SUCH_GROUP
	WRAPPER_NO_SUCH_ROOM
	WRAPPER_INVALID_RUN
	WRAPPER_INVALID_COMMANDS
	WRAPPER_INVALID_ARG
	WRAPPER_INVALID_SESSION_NAME
);

# package constants
use constant {
	OK => 0,

	START_CONF_ERROR => 50,

	WRAPPER_ERROR_BASE => 13000,
	WRAPPER_GENERAL_ERROR => 13000 -1,
	WRAPPER_PROGRAM_ERROR => 13000 -2,
	WRAPPER_UNAUTHORIZED_UID => 13000 -3,
	WRAPPER_SCRIPT_EXEC_FAILED => 13000 -6,
	WRAPPER_UNAUTHENTICATED_ID => 13000 -32,
	WRAPPER_APP_ID_DOES_NOT_EXIST => 13000 -33,
	WRAPPER_UNAUTHORIZED_ID => 13000 -34,
	WRAPPER_INVALID_GROUP => 13000 -55,
	WRAPPER_INVALID_FILENAME => 13000 -56,
	WRAPPER_INVALID_IS_EXAMPLE => 13000 -57,
	WRAPPER_INVALID_IMAGE => 13000 -58,
	WRAPPER_INVALID_ACTION => 13000 -59,
	WRAPPER_CANNOT_OPEN_FILE => 13000 -106,
	WRAPPER_CANNOT_RUN_COMMAND => 13000 -107,
	WRAPPER_INVALID_TYPE => 13000 -108,
	WRAPPER_INVALID_TARGET => 13000 -109,
	WRAPPER_NO_SUCH_HOST => 13000 -110,
	WRAPPER_NO_SUCH_GROUP => 13000 -111,
	WRAPPER_NO_SUCH_ROOM => 13000 -112,
	WRAPPER_INVALID_RUN => 13000 -113,
	WRAPPER_INVALID_COMMANDS => 13000 -114,
	WRAPPER_INVALID_ARG => 13000 -115,
	WRAPPER_INVALID_SESSION_NAME => 1300 -116,
};



1;
