use strict;
use utf8;
use base ("Error");

package Schulkonsole::Error::Sophomorix;
require Exporter;
use vars qw($VERSION @ISA @EXPORT @EXPORT_OK %EXPORT_TAGS);
$VERSION = 0.16;
@ISA = qw(Exporter);
@EXPORT_OK = qw(
	new
	what
	errstr

	WRAPPER_ON_UNDEFINED
	WRAPPER_INVALID_USER
	WRAPPER_NO_USERS
	WRAPPER_INVALID_USERID
	WRAPPER_NO_USERIDS
	WRAPPER_NO_SUCH_DIRECTORY
	WRAPPER_INVALID_DO_COPY
	WRAPPER_INVALID_FROM
	WRAPPER_INVALID_TYPE
	WRAPPER_INVALID_ROOM
	WRAPPER_INVALID_PROJECT
	WRAPPER_INVALID_PROJECT_TEACHER
	WRAPPER_INVALID_CLASS
	WRAPPER_INVALID_CLASS_TEACHER
	WRAPPER_INVALID_SUBCLASS
	WRAPPER_INVALID_DO_ADD
	WRAPPER_INVALID_SET_PASSWORD_TYPE
	WRAPPER_INVALID_PASSWORD
	WRAPPER_INVALID_IS_GROUPS
	WRAPPER_INVALID_IS_PUBLIC
	WRAPPER_INVALID_IS_UPLOAD
	WRAPPER_INVALID_PROJECTGID
	WRAPPER_INVALID_MEMBERSCOPE
	WRAPPER_INVALID_DO_CREATE
	WRAPPER_INVALID_LONGNAME
	WRAPPER_INVALID_FILENUMBER
	WRAPPER_CANNOT_OPEN_FILE
	WRAPPER_PROCESS_RUNNING
	WRAPPER_INVALID_MODE
	WRAPPER_CHMOD_FAILED
	WRAPPER_INVALID_FLAGS
	WRAPPER_INVALID_DISKQUOTA
	WRAPPER_INVALID_MAILQUOTA
	WRAPPER_INVALID_IS_JOIN
	WRAPPER_INVALID_ACTION
	WRAPPER_INVALID_FILENAME
	WRAPPER_NO_SUCH_FILE
	WRAPPER_ACTION_NOT_SUPPORTED
	WRAPPER_INVALID_FILETYPE
	WRAPPER_INVALID_COMMIT
	WRAPPER_INVALID_PAGING
	WRAPPER_INVALID_MAILADDRESS
	WRAPPER_ERROR_SETMYMAIL
);

# package constants
use constant {
	OK => 0,

	WRAPPER_ON_UNDEFINED => 8000 -80,
	WRAPPER_INVALID_USER => 8000 -81,
	WRAPPER_NO_USERS => 8000 -82,
	WRAPPER_INVALID_USERID => 8000 -83,
	WRAPPER_NO_USERIDS => 8000 -84,
	WRAPPER_NO_SUCH_DIRECTORY => 8000 -85,
	WRAPPER_INVALID_DO_COPY => 8000 -86,
	WRAPPER_INVALID_FROM => 8000 -87,
	WRAPPER_INVALID_TYPE => 8000 -88,
	WRAPPER_INVALID_ROOM => 8000 -89,
	WRAPPER_INVALID_PROJECT => 8000 -90,
	WRAPPER_INVALID_CLASS => 8000 -91,
	WRAPPER_INVALID_SUBCLASS => 8000 -92,
	WRAPPER_INVALID_IS_EXAM => 8000 -93,
	WRAPPER_INVALID_DO_ADD => 8000 -94,
	WRAPPER_INVALID_FILE_TYPE => 8000 -95,
	WRAPPER_INVALID_SET_PASSWORD_TYPE => 8000 -96,
	WRAPPER_INVALID_PASSWORD => 8000 -97,
	WRAPPER_INVALID_IS_GROUPS => 8000 -98,
	WRAPPER_INVALID_IS_PUBLIC => 8000 -99,
	WRAPPER_INVALID_IS_UPLOAD => 8000 -100,
	WRAPPER_INVALID_PROJECTGID => 8000 -101,
	WRAPPER_INVALID_MEMBERSCOPE => 8000 -102,
	WRAPPER_INVALID_DO_CREATE => 8000 -103,
	WRAPPER_INVALID_LONGNAME => 8000 -104,
	WRAPPER_INVALID_FILENUMBER => 8000 -105,
	WRAPPER_CANNOT_OPEN_FILE => 8000 -106,
	WRAPPER_PROCESS_RUNNING => 8000 -107,
	WRAPPER_INVALID_MODE => 8000 -108,
	WRAPPER_CHMOD_FAILED => 8000 -109,
	WRAPPER_INVALID_FLAGS => 8000 -110,
	WRAPPER_INVALID_DISKQUOTA => 8000 -111,
	WRAPPER_INVALID_MAILQUOTA => 8000 -112,
	WRAPPER_INVALID_IS_JOIN => 8000 -113,
	WRAPPER_INVALID_ACTION => 8000 -114,
	WRAPPER_INVALID_FILENAME => 8000 -115,
	WRAPPER_NO_SUCH_FILE => 8000 -116,
	WRAPPER_ACTION_NOT_SUPPORTED => 8000 -117,
	WRAPPER_INVALID_FILETYPE => 8000 - 118,
	WRAPPER_INVALID_CLASS_TEACHER => 8000 - 119,
	WRAPPER_INVALID_PROJECT_TEACHER => 8000 - 120,
	WRAPPER_INVALID_COMMIT => 8000 - 121,
	WRAPPER_INVALID_PAGING => 8000 - 122,
	WRAPPER_INVALID_MAILADDRESS => 8000 -123,
	WRAPPER_ERROR_SETMYMAIL => 8000 -124,
};

sub new {
	my $class = shift;
	my $this = $class->SUPER::new(@_);
	bless $this, $class;
	return $this;
}

sub what {
	my $this = shift;

	SWITCH: {
	$this->{code} == OK and return $this->{d}->get('kein Fehler');
	$this->{what} and return $this->{what};

	return SUPER::what();
	}


1;
