use strict;
use utf8;


package Schulkonsole::Error::User;
require Exporter;
use vars qw($VERSION @ISA @EXPORT @EXPORT_OK %EXPORT_TAGS);
$VERSION = 0.16;
@ISA = qw(Exporter);
@EXPORT_OK = qw(
	OK
	WRAPPER_ERROR_BASE
	WRAPPER_GENERAL_ERROR
	WRAPPER_PROGRAM_ERROR
	WRAPPER_UNAUTHORIZED_UID
	WRAPPER_INVALID_UID
	WRAPPER_INVALID_SCRIPT
	WRAPPER_SCRIPT_EXEC_FAILED
	WRAPPER_SETUID_FAILED
);

# package constants
use constant {
	OK => 0,

	WRAPPER_ERROR_BASE => 5000,
	WRAPPER_GENERAL_ERROR => 5000 -1,
	WRAPPER_PROGRAM_ERROR => 5000 -2,
	WRAPPER_UNAUTHORIZED_UID => 5000 -3,
	WRAPPER_INVALID_UID => 5000 -4,
	WRAPPER_INVALID_SCRIPT => 5000 -5,
	WRAPPER_SCRIPT_EXEC_FAILED => 5000 -6,
	WRAPPER_SETUID_FAILED => 5000 -9,
};



1;
