#! /usr/bin/perl
use strict;
use utf8;
use lib '/usr/share/schulkonsole';
use Schulkonsole::Session;

my $this_file = 'example';

my $sk_session = new Schulkonsole::Session($this_file);

$sk_session->print_page("$this_file.tt", $this_file);

