#! /usr/bin/perl

=head1 NAME

quotas - produces startpage for quota settings

=head1 SYNOPSIS

 https://server/schulkonsole/quotas

=head1 DESCRIPTION

C<quotas> produces the startpage of schulkonsole quota settings.
The HTML template is quotas.tt.

=head2 Template variables

Additionally to the variables of Schulkonsole::Session C<quotas>
provides the following variables:

=over

=cut

use strict;
use utf8;
use lib '/usr/share/schulkonsole';
use Schulkonsole::Session;
use Schulkonsole::Sophomorix;
use Sophomorix::SophomorixAPI;
use Sophomorix::SophomorixConfig;


my $this_file = 'quotas';



my $sk_session = new Schulkonsole::Session($this_file);
if (not $sk_session->get_password()) {
	my $q = new CGI;
	my $url = $q->url( -full => 1 );

	# we send cookies over secure connections only
	if ($url =~ s/^http:/https:/g) {
		$sk_session->redirect($url);
	} else {
		$sk_session->exit_with_login_page($this_file);
	}
}


$sk_session->print_page("$this_file.tt", $this_file);


=back

=head2 Form fields

none
